version: '2'

services:
  boot:
    image: activatedgeek/mariadb:devel
    build:
      context: .
    command:
      - "--wsrep-cluster-name=test_cluster"
      # @TODO this should never be empty will cause problems during restart
      - "--wsrep-cluster-address=gcomm://"
      - "--wsrep-new-cluster"
    environment:
      MYSQL_ROOT_PASSWORD: abc123

  node:
    image: activatedgeek/mariadb:devel
    build:
      context: .
    links:
      - boot
    command:
      - "--wsrep-cluster-name=test_cluster"
      - "--wsrep-cluster-address=gcomm://boot"
    environment:
      MYSQL_ROOT_PASSWORD: abc123
